[package]
name = "rekey_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
rekey_common = { path = "../rekey_common/", version = "0.1.0" }

[dependencies.windows]
version = "0.51.1"
features = ["Win32_Foundation"]
