[package]
name = "rekey_common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
chrono = "0.4.31"

[dependencies.windows]
version = "0.51.1"
features = [
  "Win32_Foundation",
]
