[package]
name = "rekey"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.51.1"
features = [
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging"
]
